### ISSUE TITLE
404 page is not styled unless it's at top level

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org#33] opened 2015-07-22 09:50 UTC
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/a is styled.
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/a/b is not.

**Comment by Bjwebb** [comment] 2015-07-22 15:20
Moved to https://github.com/NRGI/resourceprojects.org/issues/33

**Comment by caprenter** [comment] 2015-07-22 15:57
We're going to deal with this by setting all the dependency URLs in the header to / instead of {{lodspeakr.home}}

**Comment by caprenter** [comment] 2015-07-22 15:58
duplicate of https://github.com/NRGI/resourceprojects.org-frontend/issues/77

**Closed by caprenter** 2015-07-22 15:58 UTC
Labels: duplicate
